---

- name: Set Distil Collector variables for non-default collectors
  ansible.builtin.set_fact:
    distil_collector_temp_name: "{{ distil_collector.name }}"
    distil_collector_temp_description: " ({{ distil_collector.name }})"
    distil_collector_temp_base_dir: "{{ distil_base_dir }}/distil-collector-{{ distil_collector.name }}"
    distil_collector_temp_compose_project_name: "{{ distil_collector_compose_project_name_base }}-{{ distil_collector.name }}"
    distil_collector_temp_container_name: >-
      {% if distil_collector_container_name_base %}
      {{
        (distil_collector_container_name_base + '-' + distil_collector.name)

        else None
      }}
  when: distil_collector.name | default(False)

- name: Set Distil Collector variables for the default collector
  ansible.builtin.set_fact:
    distil_collector_temp_name: null
    distil_collector_temp_description: " (default collector)"
    distil_collector_temp_base_dir: "{{ distil_base_dir }}/distil-collector"
    distil_collector_temp_compose_project_name: "{{ distil_collector_compose_project_name_base }}"
    distil_collector_temp_container_name: "{{ distil_collector_container_name_base }}"
  when: distil_collector.name | default(True, True)
