---

- name: Run per-collector common tasks
  ansible.builtin.include_tasks:
    file: common.yml

- name: "Create service directory{{ distil_collector_temp_description }}"
  ansible.builtin.file:
    path: "{{ distil_collector_temp_base_dir }}"
    state: directory
    owner: root
    group: "{{ distil_docker_group }}"
    mode: "0770"

- name: "Create service README file{{ distil_collector_temp_description }}"
  ansible.builtin.template:
    src: README.md.j2
    dest: "{{ distil_collector_temp_base_dir }}/README.md"
    owner: root
    group: root
    mode: "0640"

- name: "Create collector configuration file (distil.conf){{ distil_collector_temp_description }}"
  ansible.builtin.template:
    src: distil.conf.j2
    dest: "{{ distil_collector_temp_base_dir }}/distil.conf"
    owner: root
    group: "{{ distil_user_group }}"
    mode: "0640"
  register: distil_collector_temp_config_file

- name: "Create service compose file{{ distil_collector_temp_description }}"
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ distil_collector_temp_base_dir }}/docker-compose.yml"
    owner: root
    group: "{{ distil_user_name }}"
    mode: "0640"

- name: "Mark service as changed (if mounted files are changed){{ distil_collector_temp_description }}"
  ansible.builtin.set_fact:
    distil_collector_temp_changed: "{{ distil_collector_temp_config_file.changed }}"
