---

- name: Install Distil Collector
  ansible.builtin.include_tasks:
    file: install.yml

- name: Enable Distil Collector
  ansible.builtin.include_tasks:
    file: enable.yml
  vars:
    distil_collector_temp_pull: always
    distil_collector_temp_state: >-
      {{
        'restarted'
        if (distil_base_temp_changed | default(False)) or distil_collector_temp_changed
        else 'present'
      }}
