---

- name: Run per-collector common tasks
  ansible.builtin.include_tasks:
    file: common.yml

- name: "Check if the service compose file exists{{ distil_collector_temp_description }}"
  ansible.builtin.stat:
    path: "{{ distil_collector_temp_base_dir }}/docker-compose.yml"
  register: distil_collector_temp_dockercompose_yml

- name: "Stop service containers without destroying them (if the compose file exists){{ distil_collector_temp_description }}"
  community.docker.docker_compose_v2:
    project_src: "{{ distil_collector_temp_base_dir }}"
    files:
      - docker-compose.yml
    state: stopped
  when: distil_collector_temp_dockercompose_yml.stat.exists | default(False)
