---

- name: Check if the service compose file exists
  ansible.builtin.stat:
    path: "{{ distil_exporter_base_dir }}/docker-compose.yml"
  register: distil_exporter_temp_dockercompose_yml

- name: Destroy service containers (if the compose file exists)
  community.docker.docker_compose_v2:
    project_name: "{{ distil_exporter_compose_project_name }}"
    project_src: "{{ distil_exporter_base_dir }}"
    state: absent
    remove_images: false
    remove_volumes: false
    remove_orphans: false
  when: distil_exporter_temp_dockercompose_yml.stat.exists | default(False)
