---

- name: Import common variables
  ansible.builtin.import_role:
    name: common

- name: Create service directory
  ansible.builtin.file:
    path: "{{ distil_manage_base_dir }}"
    state: directory
    owner: root
    group: docker
    mode: "0770"

- name: Create service README file
  ansible.builtin.template:
    src: README.md.j2
    dest: "{{ distil_manage_base_dir }}/README.md"
    owner: root
    group: root
    mode: "0640"

- name: Create service compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ distil_manage_base_dir }}/docker-compose.yml"
    owner: root
    group: "{{ distil_user_name }}"
    mode: "0640"
