---

- name: Import common variables
  ansible.builtin.import_role:
    name: common

- name: Check if the service compose file exists
  ansible.builtin.stat:
    path: "{{ distil_api_base_dir }}/docker-compose.yml"
  register: distil_api_temp_dockercompose_yml

- name: Stop service containers without destroying them (if the compose file exists)
  community.docker.docker_compose_v2:
    project_src: "{{ distil_api_base_dir }}"
    files:
      - docker-compose.yml
    state: stopped
  when: distil_api_temp_dockercompose_yml.stat.exists | default(False)
