---

# Distil Keystone user configuration is managed by the common role.

distil_keystone_user_roles:
  - "admin"
  - "ResellerAdmin"

distil_keystone_role_create:
  - "ResellerAdmin"

distil_keystone_service_name: "distilv2"
distil_keystone_service_description: "Distil Rating Service"
distil_keystone_service_type: "ratingv2"
distil_keystone_service_interfaces:
  - "admin"
  - "internal"
  - "public"

# When requiring explicit Keystone password auth, set the following variable.
# To ignore OpenStack environment variables from other clouds, set load_envvars to false.
# distil_keystone_ansible_auth_cloud:
#   auth_type: "password"
#   auth:
#     auth_url: "https://api.example.com:5000/v3"
#     username: "admin"
#     password: "123456"
#     project_name: "openstack"
#     user_domain_name: "Default"
#     project_domain_name: "Default"
#   verify: false
#   load_envvars: false
