---

context_is_admin: 'role:admin'
responsible_for_billing: 'role:_member_ or role:billing or role:project_admin or role:project_mod'
admin_or_owner: 'role:admin or (project_id:%(project_id)s and rule:responsible_for_billing)'
default: 'rule:admin_or_owner'

'rating:credits:get': 'rule:admin_or_owner'
'rating:measurements:get': 'rule:admin_or_owner'
'rating:invoices:get': 'rule:admin_or_owner'
'rating:quotations:get': 'rule:admin_or_owner'
'health:get': 'rule:context_is_admin'
