---

- name: Import common variables
  ansible.builtin.import_role:
    name: common

# NOTE(callumdickinson): Add tasks to run after completing the deploy here.
# Examples include cleaning up old service files.
