---

- name: Deploy Distil (nodes running all services)
  hosts: distil
  become: true
  serial: 1
  tasks:
    - name: Run pre-deploy tasks for Distil Collector
      ansible.builtin.include_role:
        name: catalystcloud.distil.collector
        tasks_from: predeploy
    - name: Run pre-deploy tasks for Distil Exporter
      ansible.builtin.include_role:
        name: catalystcloud.distil.exporter
        tasks_from: predeploy
    - name: Run pre-deploy tasks for Distil API
      ansible.builtin.include_role:
        name: catalystcloud.distil.api
        tasks_from: predeploy
    - name: Run pre-deploy tasks for Distil Base
      ansible.builtin.include_role:
        name: catalystcloud.distil.base
        tasks_from: predeploy
    - name: Deploy Distil Base
      ansible.builtin.include_role:
        name: catalystcloud.distil.base
    - name: Deploy Distil API
      ansible.builtin.include_role:
        name: catalystcloud.distil.api
    - name: Deploy Distil Exporter
      ansible.builtin.include_role:
        name: catalystcloud.distil.exporter
    - name: Deploy Distil Collector
      ansible.builtin.include_role:
        name: catalystcloud.distil.collector
    - name: Run post-deploy tasks for Distil Collector
      ansible.builtin.include_role:
        name: catalystcloud.distil.collector
        tasks_from: postdeploy
    - name: Run post-deploy tasks for Distil Exporter
      ansible.builtin.include_role:
        name: catalystcloud.distil.exporter
        tasks_from: postdeploy
    - name: Run post-deploy tasks for Distil API
      ansible.builtin.include_role:
        name: catalystcloud.distil.api
        tasks_from: postdeploy
    - name: Run post-deploy tasks for Distil Base
      ansible.builtin.include_role:
        name: catalystcloud.distil.base
        tasks_from: postdeploy
