---

- name: Run post-deploy tasks for Distil API
  hosts: distil:distil_api
  become: true
  serial: 1
  tasks:
    - name: Run post-deploy tasks for Distil API
      ansible.builtin.include_role:
        name: catalystcloud.distil.api
        tasks_from: postdeploy
