---

- name: Run pre-deploy tasks for Distil Collector
  hosts: distil:distil_collector
  become: true
  serial: 1
  tasks:
    - name: Run pre-deploy tasks for Distil Collector
      ansible.builtin.include_role:
        name: catalystcloud.distil.collector
        tasks_from: predeploy
