---

- name: Stop Distil API
  hosts: distil:distil_api
  become: true
  serial: 1
  tasks:
    - name: Stop Distil API
      ansible.builtin.include_role:
        name: catalystcloud.distil.api
        tasks_from: stop
