---

- name: Uninstall Distil Manage
  hosts: distil:distil_manage
  become: true
  serial: 1
  tasks:
    - name: Uninstall Distil Manage
      ansible.builtin.include_role:
        name: catalystcloud.distil.manage
        tasks_from: uninstall
