name: test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.1

  build:
    runs-on: ubuntu-22.04
    needs: pre-commit
    steps:
      - name: Checkout release
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: pip
      - name: Install pipeline Python packages
        run: python -m pip install -r requirements.txt
        env:
          FORCE_COLOR: "1"
      - name: Build collection
        run: ansible-galaxy collection build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: catalystcloud-distil-*.tar.gz
          retention-days: 5

  molecule:
    runs-on: ubuntu-22.04
    needs: build
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - install
          - upgrade
          - ssl_disable
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Setup Docker Compose
        uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: "2.27.0"
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: pip
      - name: Install pipeline Python packages
        run: python -m pip install -r requirements.txt
        env:
          FORCE_COLOR: "1"
      - name: Run Molecule tests
        run: molecule test --scenario-name ${{ matrix.scenario }}
        env:
          ANSIBLE_FORCE_COLOR: "True"
